# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO.xci
# IP: The module: 'FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO/FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO/FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO.xci
# IP: The module: 'FIFO' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO/FIFO.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO/FIFO_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/Workspace/Vivado_16.4/2017_11_17_Pingpang_RAM/Design/IP_Core/FIFO/FIFO/FIFO_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
